[buildPlans.Sevka]
family = "Sevka"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.Sevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Sevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Sevka.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.Sevka.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Sevka.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.Sevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Sevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Sevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.SevkaSlab]
family = "Sevka Slab"
spacing = "quasi-proportional"
serifs = "slab"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.SevkaSlab.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.SevkaSlab.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.SevkaSlab.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.SevkaSlab.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.SevkaSlab.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.SevkaSlab.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.SevkaSlab.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.SevkaSlab.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.SevkaFixed]
family = "Sevka Fixed"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.SevkaFixed.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.SevkaFixed.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.SevkaFixed.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.SevkaFixed.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.SevkaFixed.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.SevkaFixed.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.SevkaFixed.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.SevkaFixed.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
